version: '3'

services:

  malexer-twemproxy:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   DEBUG: false
    image: ghcr.io/usaldudo/docker-twemproxy:0.5.1
    container_name: twemproxy
    environment:
      REDIS_SERVERS: "127.0.1.1:6379:1 server1,127.0.1.2:6379:1 server2,127.0.1.3:6379:1 server3"
      # REDIS_SENTINEL_SERVERS: "127.0.0.1:26379:1,127.0.0.1:26380:1,127.0.0.1:26381:1"
    ports:
      - 6380:6380
